name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout   
        uses: node16

      - name: Cypress run
        uses: node16
        with: 
          build: npm run build
          start: npm start
